In [24]:
import numpy as np
from numpy import linalg as lng

In [21]:
# arrays in NP are vectors
a = np.array([20,40,60])
b = np.array([10,20,30])
c = np.array([5,10,15,20])

# sum/subtraction/multiply/divide operation using numpy would result in the sum/subtraction/multiply/divide of the vectors
# unlike summing lists in python which would concatenate the list or other operations which would result in different behaviors
print(a + b)
print(a - b)
print(a * b)
print(a/b)

[30 60 90]
[10 20 30]
[ 200  800 1800]
[2. 2. 2.]


In [19]:
# operations can not happen between two vectors with different size, this would result in a ValueError
a + c

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [48]:
scalar = 2
python_list = [10,11,12,13,14,15]
np_array = np.array(python_list)

# multiplying a Python list with a number (eg scalar) would result in the list being concatenated with itself X times
print(python_list * scalar)
# multiplying a numpy array with a number would result in every item in the np array being multiply by the number
print(np_array * scalar)

[10, 11, 12, 13, 14, 15, 10, 11, 12, 13, 14, 15]
[20 22 24 26 28 30]


In [22]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
x = np.array([[1,2,3,4]])
z = np.array([[1],
              [2],
              [3],
              [4]])

# to determine the shape of our vector we can use numpy shape function
print(np.shape(a))
print(np.shape(b))
print(np.shape(x))
print(np.shape(z))

# a dot product of two vectors is the multiplication of each item in the array with its corresponding items in the other array
# she shapes of the vectors must align to be able to find their dot value
print(np.dot(a,b))
print(np.dot(b,a))
print(np.dot(x,z))
print(np.dot(z,x))
# this won't work as the shapes don't align and would result in a ValueError
print(np.dot(a,x))

(4,)
(4,)
(1, 4)
(4, 1)
70
70
[[30]]
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


ValueError: shapes (4,) and (1,4) not aligned: 4 (dim 0) != 1 (dim 0)

In [23]:
c = np.array([11, 12, 13, 14])

# the first result and the second result would result in the same value
first_result = np.dot(a, b+c)
print(first_result)
second_result = np.dot(a,b) + np.dot(a,c)
print(second_result)

200


In [25]:
# linlng.norm function allow us to calculate the norm of a vector
lng.norm(a)

5.477225575051661

In [27]:
# to calc vector projection we can use the following
vector_projection = (np.dot(a,b)/np.dot(b,b))*b
print(vector_projection)

array([2.36363636, 2.75757576, 3.15151515, 3.54545455, 3.93939394])

In [27]:
a = np.array([[1,2],
              [3,4]])

# we can invert vector a using lng.inv
print(a)
print(lng.inv(a))

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [32]:
b = np.array([5,11])
x = np.dot(lng.inv(a),b)
# x is now the dot value of a inverted and b
print(x)
# we can get the value of b by calculating the dot value of a and x
print(f'b is: {np.dot(a,x)}')

[1. 2.]
b is: [ 5. 11.]


In [47]:
# to calculate the det of a we can use lng.det
print(f'det: {lng.det(a)}')
# this is useful in detraining if a vector can be inverted
print(lng.inv(a))

det: -2.0000000000000004


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [33]:
# as we can't invert matrixes with det == 0 as this would result in a LinAlgError
C = np.array([[3,1],
              [6,2]])
print(f'det: {lng.det(C)}')
lng.inv(C)

det: 0.0


LinAlgError: Singular matrix